# PROJECT: dolphin-admin
# VERSION: 1.0.0
# Author: wangxiang4

# https://support.websoft9.com/docs/docker/zh/solution-compose.html#command
version: '3'
services:
  dolphin-admin:
    build:
      context: .
    restart: always
    container_name: dolphin-admin
    image: dolphin-admin
    networks:
      - docker-cloud_default
    external_links:
      - dolphin-gateway
    ports:
      - 80:80

networks:
  docker-cloud_default:
    external: true
